config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :friendships, only: [:create, :destroy]
  end

  #use patch instead of put to update only :accepted attribute
  patch 'friendships/:id/accept/', to: 'friendships#accept', as: 'accept_friendship'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user_id, presence: true
  validates :friend_id, presence: true
  validates :accepted, inclusion: { in: [true, false] }

  validates :user_id, uniqueness: { scope: :friend_id, message: 'is already a friend' }

  scope :pending, lambda { |user|
    joins(:user)
      .where(friend_id: user.id, accepted: false)
  }

  scope :accepted_friends_ids, lambda { |user|
    joins(:user)
      .where(user_id: user.id, accepted: true).pluck(:friend_id)
      .concat(joins(:friend)
    .where(friend_id: user.id, accepted: true).pluck(:user_id))
  }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

  scope :timeline, lambda { |user|
    where(user_id: Friendship.accepted_friends_ids(user))
      .or(where(user_id: user.id))
      .order(created_at: :desc)
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships

  validates :email, presence: true, uniqueness: true

  scope :available, lambda { |user|
    where.not(id: user.friends.ids)
      .where.not(id: user.id)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      redirect_to posts_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = Friendship.pending
  end

  def show
    @friendship = Friendship.find(params[:id])
  end

  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new
    @friendship.user_id = current_user.id
    @friendship.friend_id = params[:friend_id]
    @friendship.accepted = false

    if @friendship.save
      render json: @friendship, status: :created, location: @friendship
    else
      render json: @friendship.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @friendship = Friendship.find(user_id: current_user.id, friend_id: params[:friend_id])
    @friendship.destroy
  end

  def accept
    @friendship = Friendship.find(params[:id])
    @friendship.accepted = true
    if @friendship.save
      redirect_to posts_path, notice: 'Friendship accepted!'
    else
      redirect_to posts_path, alert: 'Error accepting friendship!'
    end
  end

  private

  def friendship_params
    params.require(:friendship).permit(:id, :friend_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_new.html.erb
<%= form_with model: Comment.new, url: "posts/#{post.id}/comments" do |f| %>  
  <%= f.label :body, "Comment" %>
  <%= f.text_area :body, :class => "comment_body" %>
  <%= f.submit %>
<% end %>

app/views/friendships/_pending.html.erb
<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
<% friendships=Friendship.pending(current_user) %>
<% if !friendships.empty? %>
  <% friendships.each do |invitation| %>  
    <li>
      <span><%= invitation.user.name %></span>
      <%= link_to 'Accept', accept_friendship_path(id: invitation.id), method: :patch  %>
    </li>
  <% end %>
<% else %>
  <li>There are no pending invitations</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends4rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="p-3">    
    <%= render 'shared/navbar' %>          
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h1 class="m-4">Posts</h1>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</div>

<% Post.timeline(current_user).each do |post| %>
  <div class="card m-4">
    <div class="card-body d-flex flex-md-row align-items-center">
        <div class="me-4">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text">By: <span class="text-muted"><%= post.user.name %></span></p>
          <p class="card-text"><%= post.body %></p>                    
        </div>
        <a href="/posts/<%= post.id %>" class="btn btn-primary">Read more</a>
    </div>    
    <%= render "comments/new", post: post %>
    <div class="accordion" id="accordionComments">
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading<%=post.id%>">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=post.id%>" aria-expanded="true" aria-controls="collapse<%=post.id%>">
            Comments
          </button>
        </h2>
        <div id="collapse<%=post.id%>" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionComments">
          <div class="accordion-body">
            <% unless post.comments.empty? %>
              <% post.comments.each do |comment| %>
                <div class="card m-4">
                  <div class="card-body">                      
                      <p class="card-text">By: <span class="text-muted"><%= comment.user.name %></span></p>
                      <p class="card-text"><%= comment.body %></p>                    
                  </div>
                </div>
              <% end %>
            <% else %>
              <p>No comments yet</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>      

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Friends4rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>          
          <%= render 'friendships/pending' %>          
        </li>
        <% end %>
      </ul>
    </div>
    <div>
      <% if signed_in? %>
        <%= link_to "Salir", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Registrarse", new_user_registration_path %>
        <%= link_to "Ingresar", new_user_session_path %>
      <% end %>
    </div>
  </div>
</nav>